### ISSUE TITLE
Related Packages

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3forecasting#10]
In this issue, I aim to collect packages related to our package.
This should enable us to compare implementations and functionality.

- [forecastIML](https://github.com/nredell/forecastML)

**Comment by jonekeat** [comment]
Hi @pfistfl 

It is really interesting to see mlr also developing time series learner. So I just want to recommend another new time series modelling package for you to compare

- [fable](https://github.com/tidyverts/fable)

It seem quite promising and Rob J Hyndman being one of the author.

**Comment by pfistfl** [comment]
Hey, @jonekeat 
Thanks for getting involved.

We actually like Prof. Hyndman's work a lot and orient the stuff we aim to do in his book. 

With respect to software, we have a slightly different philosophy:
- We aim for objects that we can program on in favor of the more interactive `tidy` approaches
- We try to have as little dependencies as possible.

**Comment by corneliagru** [comment]
closing, since not relevant anymore
