### ISSUE TITLE
Orientation Packages & Package Design

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3forecasting#11]
So a few general questions came up today, which I will try to answer here:
- What can we look at in order to understand the general structure we should strive towards?
  - For `spatiotemporal` data we have (https://github.com/mlr-org/mlr3spatiotempcv).
    Here they define new Resampling Methods and perhaps also Data structures for `mlr3`.
    I think this might actually be the best way to start.

- What package(s) do we want to build on top of?
  - https://github.com/mlr-org/mlr3 -> Basics like Task / Learner Classes etc.
  - https://github.com/mlr-org/mlr3misc -> Many valuable helper functions
  - https://github.com/mlr-org/paradox -> Defining Hyperparameters.

**Comment by corneliagru** [comment]
closing, since not relevant anymore
