### ISSUE TITLE
LearnerForecast Class Hierarchy

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3forecasting#33]
We currently have the following hierarchy in `LearnerForecast`

- [ ] `LearnerForecast` (abstract)
  - [ ] `LearnerForecastAverage` 
  - [ ] `LearnerRegrForecastAutoArima` 
  - [ ] `LearnerRegrForecastVAR` 

- Does it make sense to have an abstract `LearnerRegrForecast` that does type-checking 
  of variable types? 
  Here we should think about future possible tasks, i.e. forecasting time-series of factors.
- I guess in any case we should either drop `Regr` naming in the two learners or 
  add it to `ForecastAverage`.

**Comment by corneliagru** [comment]
our idea was to have the abstract class LearnerForecast. Then it is possible to have the classes LearnerRegrForecast for regression problems and if the package will be extended with other time series methods like Classification it is possible to have a class LearnerClassifForeacst. 

Therfore renaming ForecastAverage to ForecastRegrAverage is our preferred choice.

**Comment by corneliagru** [comment]
we changed LearnerForecastAverage to LearnerRegrForecastAverage as proposed. See #48
